version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: 'ecommerce_rabbitmq'
    ports:
      - 5673:5672
      - 15673:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq/
    networks:
      - rabbitmq_network
  order:
    image: latifismail/order-service:latest
    container_name: 'ecommerce_order'
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
    volumes: 
      - ./order-service/:/app/
      - /app/node_modules
    networks:
      - rabbitmq_network
    depends_on:
      - rabbitmq
  shipping:
    image: latifismail/shipping-service:latest
    container_name: 'ecommerce_shipping'
    ports:
      - 3001:3001
    environment:
      PORT: 3001
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
    volumes: 
      - ./shipping-service/:/app/
      - /app/node_modules
    networks:
      - rabbitmq_network
    depends_on:
      - rabbitmq
volumes:
  rabbitmq_data:
  rabbitmq_log:
networks:
  rabbitmq_network:
    driver: bridge