apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    app: karsajobs
spec:
  selector:
    matchLabels:
      app: karsajobs
      tier: data
  serviceName: mongo
  replicas: 2
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: karsajobs
        tier: data
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo-image
        image: mongo
        ports:
        - containerPort: 27017
          protocol: TCP
        env:
        - name: MONGO_INITDB_ROOT_USERNAME_FILE
          value: /etc/mongo-credentials/MONGO_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD_FILE
          value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD
        volumeMounts:
        - name: mongo-pv-volume
          mountPath: /data/db
        - name: mongo-config
          mountPath: /config
        - name: mongo-secret
          mountPath: /etc/mongo-credentials
      volumes:
      - name: mongo-pv-volume
        persistentVolumeClaim:
          claimName: mongo-pv-claim
      - name: mongo-config
        configMap:
          name: mongo-config
      - name: mongo-secret
        secret:
          secretName: mongo-secret