apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: karsajobs
spec:
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30077
  selector:
    tier: frontend
  type: NodePort